---
title: "Knowledge and Learning Synthesis Paper"
author: "Meghan Fletcher"
date: "3/9/2022"
output: 
  html_document:
    theme: flatly
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE, message = FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

```

# Load data

```{r}
library(here)
source(here("case_study_analysis","mf_clustering_analysis","00-load-libraries.R"))
load(here("case_study_analysis","mf_clustering_analysis","data","attribs.Rdata")) # from 01-prep-data.Rmd
load(here("case_study_analysis","mf_clustering_analysis","data","attributes_merged_clean.Rdata"))
load(here("case_study_analysis","mf_clustering_analysis","data","case_study_attribute_score_data.csv")) # From Chris's cleaned data
```

# Clean data

```{r}
# Need to clean Chris's data to create a column with numeric importance value

clean_data <- data %>% 
  mutate(numeric_importance = case_when(
    importance == "low" ~ "1",
    importance == "medium" ~ "2",
    importance == "high" ~ "3",
    importance == "NA" ~ "0")) %>% 
  mutate(numeric_importance=as.numeric(numeric_importance))
```


##################################################################################################

# Knowledge and Learning Attributes Clustering

```{r}
# Create a subset of data with only the knowledge and learning attributes
knowledge_data <- clean_data %>% 
  select(case_study, attribute, score, numeric_importance) %>% 
  filter(attribute %in% c("Knowledge diversity", "Knowledge access", "Learning capacity", "Adaptive"))
```

## Clustering Analyses for Attibute Score

```{r}
# Dendrogram based on hclust
knowledge_clust <- knowledge_data %>% 
  select(case_study, attribute, score) %>% 
  pivot_wider(names_from = attribute, values_from = score)
 
knowledge_hc <- knowledge_clust %>% 
  column_to_rownames(var = "case_study") %>% 
  mutate(across(everything(),~scale(.x))) %>% 
  mutate(across(everything(), ~replace_na(.x, 0))) %>% # REVIEW
  as.matrix() %>% 
  dist() %>% hclust(method = "ward.D2")


plot(knowledge_hc)

library(ape)
plot(as.phylo(knowledge_hc), type = "unrooted", cex = 0.6,
     no.margin = TRUE)

# Fan plot
#plot(as.phylo(knowledge_hc), type = "fan")

library(ggdendro)
#ggdendrogram(knowledge_hc, rotate = TRUE, theme_dendro = FALSE)
```


## Clustering Analyses for Importance

```{r}
# Dendrogram based on hclust
knowledge_importance_clust <- clean_data %>% 
  select(case_study, attribute, numeric_importance) %>% 
  pivot_wider(names_from = attribute, values_from = numeric_importance)
 
knowledge_importance_hc <- knowledge_importance_clust %>% 
  column_to_rownames(var = "case_study") %>% 
  mutate(across(everything(),~scale(.x))) %>% 
  mutate(across(everything(), ~replace_na(.x, 0))) %>% # REVIEW
  as.matrix() %>% 
  dist() %>% hclust(method = "ward.D2")


plot(knowledge_importance_hc)

library(ape)
plot(as.phylo(knowledge_importance_hc), type = "unrooted", cex = 0.6,
     no.margin = TRUE)

library(ggdendro)
ggdendrogram(knowledge_importance_hc, rotate = TRUE, theme_dendro = FALSE)
```




