---
title: "Importance Summary Statistics"
author: "Meghan Fletcher"
date: "2/14/2022"
output: 
  html_document:
    theme: flatly
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE, message = FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

```

# Load data

```{r}
library(here)
source(here("00-load-libraries.R"))
load(here("data","summary_clean.Rdata")) 
```

################################################################################################

# Group data into tables

## Table for most important

```{r}
dimension_table <- case_study_summary %>% 
  select(case_study, case_study_author, most_important_dimension) %>% 
  rename("Case Study" = case_study,
         Author = case_study_author,
         "Most Important Dimension" = most_important_dimension)

# Create a table
dimension_table %>% 
  kbl(caption = "Most Important Dimensions Across Case Studies") %>% 
   kable_classic_2(full_width = F, html_font = "Cambria") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))
```


## Table for most important domains

```{r}
domain_importance_table <- case_study_summary %>% 
  select(case_study, case_study_author, highest_importance_domain, second_highest_importance_domain, third_highest_importance_domain) %>% 
  rename("Case Study" = case_study,
         Author = case_study_author,
         "Most Important Domain" = highest_importance_domain,
         "Second Most Important Domain" = second_highest_importance_domain,
         "Third Most Important Domain" = third_highest_importance_domain)

# Create a table
domain_importance_table %>% 
  kbl(caption = "Top 3 Most Important Domains Across Case Studies") %>% 
   kable_classic_2(full_width = F, html_font = "Cambria") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))
```


## Highest scoring domains stats

```{r}
# Make a table of the highest scoring domains - put counts and percentages into table 
domain_table <- case_study_summary %>% 
  select(highest_importance_domain, second_highest_importance_domain, third_highest_importance_domain) %>% 
  rename(First = highest_importance_domain,
         Second = second_highest_importance_domain,
         Third = third_highest_importance_domain) %>% 
  pivot_longer(
    everything()) %>% 
  rename(Rank = name,
         Domain = value)


domain_stats <- domain_table %>% 
  select(Rank, Domain) %>% 
  tabyl(Rank,Domain) %>%
  adorn_percentages() %>% 
  adorn_pct_formatting(digits = 2) 

# Create a table
domain_stats %>% 
  kbl(caption = "Proportion of Domains Listed as Most Important") %>% 
   kable_classic_2(full_width = F, html_font = "Cambria") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))
```


#########################################################################################################

# Visualize the data

```{r}
# Create theme
my_theme <-  theme(axis.text.x=element_text(size=9, angle=38, hjust=1),
                   axis.text.y=element_text(size=9),
                   legend.text=element_text(size=8),
                   legend.title=element_text(size=9),
                   strip.text=element_text(size=9),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_rect(), 
                   axis.line = element_line())
```


## Break it down by fishery arechtype

### Small-scale vs. Large-scale Dimension Scoring
```{r}
ggplot(case_study_summary, aes(x=most_important_dimension, fill=fishery_scale_small_or_large)) +
  geom_bar() +
  facet_wrap(~fishery_scale_small_or_large) +
  theme_bw() + my_theme +
  labs(title = "Most Important Dimensions by Fishery Scale", x = "Dimension", y = "Count", fill = "Fishery Scale")
```


### Fishery location
```{r}
ggplot(case_study_summary, aes(x=most_important_dimension, fill=fishery_location)) +
  geom_bar() +
  facet_wrap(~fishery_location) +
  theme_bw() +my_theme +
  labs(title = "Most Important Dimensions by Fishery Location", x = "Dimension", y = "Count", fill = "Fishery Location") +
  scale_fill_viridis(discrete=TRUE)
```


## Vizualize highest scoring domains

```{r}
# Make a graph for counts of  highest scoring domains
ggplot(domain_table, aes(x=Domain, fill = Rank)) +
  geom_bar() +
  theme_bw() + my_theme +
  labs(title = "Most Important Domains", y = "Count") +
  scale_fill_viridis(discrete=TRUE)
  
```


