---
title: "Survey-Response-Analysis"
author: "Robert Saldivar"
date: "9/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document will be used to analyze survey responses

```{r}
#Loading the nessecary packages
library(tidyverse)
library(googlesheets4)
library(here)
library(janitor)

#for text mining open responses
library(tidytext)
library(textdata)
library(ggwordcloud)

```

```{r}

#gs4_auth() # Run this in console with your email address. It allow R to access your google sheets

```

###############################################################################################################################################
Test Analysis

```{r}
Test_section0 <- read_sheet(ss = "https://docs.google.com/spreadsheets/d/1vcWRmro97z5HXzoKhaAK4nrhFJwghCI2oCLEAeHnwD4/edit?usp=drive_web", 
                           sheet = "0_YourName",
                           range = "A4:C5",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

test_section1 <-read_sheet(ss = "https://docs.google.com/spreadsheets/d/1vcWRmro97z5HXzoKhaAK4nrhFJwghCI2oCLEAeHnwD4/edit?usp=drive_web", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names() #%>%
  #remove_empty(which = c("rows", "cols")) #not sure if the remove will be best when analyzing multiple sheets

test_section2 <- read_sheet(ss ="https://docs.google.com/spreadsheets/d/1vcWRmro97z5HXzoKhaAK4nrhFJwghCI2oCLEAeHnwD4/edit?usp=drive_web", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

test_section3 <- read_sheet(ss ="https://docs.google.com/spreadsheets/d/1vcWRmro97z5HXzoKhaAK4nrhFJwghCI2oCLEAeHnwD4/edit?usp=drive_web", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

test_section4 <- read_sheet(ss ="https://docs.google.com/spreadsheets/d/1vcWRmro97z5HXzoKhaAK4nrhFJwghCI2oCLEAeHnwD4/edit?usp=drive_web", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

test_section5 <- read_sheet(ss ="https://docs.google.com/spreadsheets/d/1vcWRmro97z5HXzoKhaAK4nrhFJwghCI2oCLEAeHnwD4/edit?usp=drive_web", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:H15",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

```

This will be for testing analysis
```{r}
#Reading in test data
test_analysis1 <- read_sheet(ss ="https://docs.google.com/spreadsheets/d/1D-ktJpRK8qHCU1HtcyiUZVP6G6fhSE4Pfm5W12KMYB8/edit?usp=sharing", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

test_analysis2 <- read_sheet(ss ="https://docs.google.com/spreadsheets/d/16WgYKtJSccJ9Fk0qOmD-CuCRO8NH1DBYfes6Fcdlkn8/edit?usp=sharing", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()
```

```{r}
#Analysing data

#This is binding the response sheets together into one sheet so it will be easier to analyze
test_section4_bind <- bind_rows(test_analysis1, test_analysis2, test_section4)

#This is filtering to a specific question so that the question can be analyzed
test_section4_bind_filter1 <- test_section4_bind %>%
  filter(question_id == "4.1.1.1")

# Analyzing a multiple choice questions performinging  a count
s4q1_count <- count(test_section4_bind_filter1, test_section4_bind_filter1$score_1_4)

s4_data_quality_count <- count(test_section4_bind, test_section4_bind$information_quality)

s4_mechanism <- count(test_section4_bind, test_section4_bind$does_the_mechanism_work_as_described_in_your_system)


# This is making bar graphs of the counts.
mechanism_plot <- ggplot(test_section4_bind, aes(x = does_the_mechanism_work_as_described_in_your_system)) +
  geom_bar()

s4_data_quality_plot <- ggplot(test_section4_bind, aes(x = information_quality)) +
  geom_bar()


#This calling the counts and plots to be displayed
s4q1_count
s4_data_quality_count
s4_mechanism
mechanism_plot
s4_data_quality_plot


```

```{r echo=FALSE}
# This will be for testing text analysis

#This gives each word used in the notes column its own cell for further analysis
s4_notes_tokens_test <- test_section4_bind %>%
  unnest_tokens(word, notes) %>%
  select(word) %>%
  drop_na()

#This is creating a count from highest to lowest of all the words
s4_notes_wc_test <- s4_notes_tokens_test %>%
  count(word) %>%
  arrange(-n) 

#This removes numbers and stop words (e.g. the, and, ect.)
s4_notes_no_stop_numeric_test <- s4_notes_tokens_test %>%
  anti_join(stop_words) %>%
  dplyr::filter(is.na(as.numeric(word)))

#Below here will be making a word cloud

#This code chunk is taking the top 100 words from this columns
s4_notes_100_test <- s4_notes_no_stop_numeric_test %>%
  count(word) %>%
  arrange(-n) %>%
  head(100)

#This creates a word cloud of the 100 words
notes_cloud_test <- ggplot(data = s4_notes_100_test, aes(label = word, size = n)) +
  geom_text_wordcloud(aes(color = n), shape = "diamond") +
  scale_size_area(max_size = 15) +
  #scale_color_gradient(colors = c("darkgreen", "blue", "purple")) +
  theme_minimal()

notes_cloud_test


```


###############################################################################################################################################
Section 1 Analysis

```{r, include=FALSE}
#This will read in all of the data for section 1

respondant1_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant2_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant3_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant4_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant5_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant6_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant7_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant8_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant9_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant10_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant11_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant12_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant13_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant14_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant15_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant16_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant17_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant18_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant19_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant20_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant21_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant22_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant23_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant24_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant25_s1 <-read_sheet(ss = "", 
                           sheet = "S1_KeyCaseIdentifiers",
                           range = "A9:P18",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

s1_bind <- bind_rows(respondant1_s1, respondant2_s1, respondant3_s1, respondant4_s1, respondant5_s1, respondant6_s1, respondant7_s1, respondant8_s1, respondant9_s1, respondant10_s1, respondant11_s1, respondant12_s1, respondant13_s1, respondant14_s1, respondant15_s1, respondant16_s1, respondant17_s1, respondant18_s1, respondant19_s1, respondant20_s1, respondant21_s1, respondant22_s1, respondant23_s1, respondant24_s1, respondant25_s1)

```

```{r, echo=FALSE}
# Text mining the species of fish that are fished

species_count <- s1_bind %>%
  filter(question_id = "1.2.1.") %>%
  unnest_tokens(species, if_describe_write_here) %>%
  select(species) %>%
  count(species) %>%
  arrange(-n)

species_plot <- ggplot(species_count, aes(x = species)) +
  geom_bar()
    
species_plot

```

```{r}
# Analysis of Questions 1.6.1. and 1.7.1.


```

```{r}
#information Quality Analysis

s1_data_quality_count <- count(s1_bind, s1_bind$information_quality)

s1_data_quality_plot <- ggplot(s1_bind, aes(x = information_quality)) +
  geom_bar()

s1_data_quality_count
s1_data_quality_plot

```

```{r echo=FALSE}
# This will be for testing text analysis

s1_notes_tokens <- s4_bind %>%
  unnest_tokens(word, notes) %>%
  select(word) %>%
  drop_na()

s1_notes_wc <- s1_notes_tokens %>%
  count(word) %>%
  arrange(-n) 

s1_notes_no_stop_numeric <- s1_notes_tokens %>%
  anti_join(stop_words) %>%
  dplyr::filter(is.na(as.numeric(word)))

#Below here will be making a word cloud

s1_notes_100 <- s1_notes_no_stop_numeric %>%
  count(word) %>%
  arrange(-n) %>%
  head(100)

s1_notes_cloud <- ggplot(data = s1_notes_100, aes(label = word, size = n)) +
  geom_text_wordcloud(aes(color = n), shape = "diamond") +
  scale_size_area(max_size = 15) +
  #scale_color_gradient(colors = c("darkgreen", "blue", "purple")) +
  theme_minimal()

s1_notes_cloud


```


###############################################################################################################################################
Section 2 Analysis

```{r, include=FALSE}
#This will read in all of the data for section 2

respondant1_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant2_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant3_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant4_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant5_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant6_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant7_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant8_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant9_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant10_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant11_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant12_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant13_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant14_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant15_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant16_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant17_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant18_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant19_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant20_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant21_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant22_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant23_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant24_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant25_s2 <-read_sheet(ss = "", 
                           sheet = "S2_ContextualDescription",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

s2_bind <- bind_rows(respondant1_s2, respondant2_s2, respondant3_s2, respondant4_s2, respondant5_s2, respondant6_s2, respondant7_s2, respondant8_s2, respondant9_s2, respondant10_s2, respondant11_s2, respondant12_s2, respondant13_s2, respondant14_s2, respondant15_s2, respondant16_s2, respondant17_s2, respondant18_s2, respondant19_s2, respondant20_s2, respondant21_s2, respondant22_s2, respondant23_s2, respondant24_s2, respondant25_s2)

```

```{r}
#information Quality Analysis

s2_data_quality_count <- count(s12_bind, s2_bind$information_quality)

s2_data_quality_plot <- ggplot(s2_bind, aes(x = information_quality)) +
  geom_bar()

s2_data_quality_count
s2_data_quality_plot

```

```{r echo=FALSE}
# This will be for testing text analysis

s2_notes_tokens <- s2_bind %>%
  unnest_tokens(word, notes) %>%
  select(word) %>%
  drop_na()

s2_notes_wc <- s2_notes_tokens %>%
  count(word) %>%
  arrange(-n) 

s2_notes_no_stop_numeric <- s2_notes_tokens %>%
  anti_join(stop_words) %>%
  dplyr::filter(is.na(as.numeric(word)))

#Below here will be making a word cloud

s2_notes_100 <- s2_notes_no_stop_numeric %>%
  count(word) %>%
  arrange(-n) %>%
  head(100)

s2_notes_cloud <- ggplot(data = s2_notes_100, aes(label = word, size = n)) +
  geom_text_wordcloud(aes(color = n), shape = "diamond") +
  scale_size_area(max_size = 15) +
  #scale_color_gradient(colors = c("darkgreen", "blue", "purple")) +
  theme_minimal()

s2_notes_cloud


```

###############################################################################################################################################
Section 3 Analysis

```{r, include=FALSE}
#This will read in all of the data for section 3

respondant1_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant2_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant3_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant4_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant5_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant6_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant7_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant8_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant9_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant10_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant11_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant12_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant13_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant14_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant15_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant16_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant17_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant18_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant19_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant20_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant21_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant22_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant23_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant24_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant25_s3 <-read_sheet(ss = "", 
                           sheet = "S3_ClimateResilientActions",
                           range = "A9:H29",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

s3_bind <- bind_rows(respondant1_s3, respondant2_s3, respondant3_s3, respondant4_s3, respondant5_s3, respondant6_s3, respondant7_s3, respondant8_s3, respondant9_s3, respondant10_s3, respondant11_s3, respondant12_s3, respondant13_s3, respondant14_s3, respondant15_s3, respondant16_s3, respondant17_s3, respondant18_s3, respondant19_s3, respondant20_s3, respondant21_s3, respondant22_s3, respondant23_s3, respondant24_s3, respondant25_s3)

```

```{r}
# Text mining the Response

```

```{r}
#information Quality Analysis

s3_data_quality_count <- count(s3_bind, s3_bind$information_quality)

s3_data_quality_plot <- ggplot(s3_bind, aes(x = information_quality)) +
  geom_bar()

s3_data_quality_count
s3_data_quality_plot

```

```{r echo=FALSE}
# This will be for testing text analysis

s3_notes_tokens <- s3_bind %>%
  unnest_tokens(word, notes) %>%
  select(word) %>%
  drop_na()

s3_notes_wc <- s3_notes_tokens %>%
  count(word) %>%
  arrange(-n) 

s3_notes_no_stop_numeric <- s3_notes_tokens %>%
  anti_join(stop_words) %>%
  dplyr::filter(is.na(as.numeric(word)))

#Below here will be making a word cloud

s3_notes_100 <- s3_notes_no_stop_numeric %>%
  count(word) %>%
  arrange(-n) %>%
  head(100)

s3_notes_cloud <- ggplot(data = s3_notes_100, aes(label = word, size = n)) +
  geom_text_wordcloud(aes(color = n), shape = "diamond") +
  scale_size_area(max_size = 15) +
  #scale_color_gradient(colors = c("darkgreen", "blue", "purple")) +
  theme_minimal()

s3_notes_cloud


```

###############################################################################################################################################
Section 4 Analysis

```{r, include=FALSE}
#This will read in all of the data for section 4

respondant1_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant2_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant3_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant4_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant5_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant6_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant7_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant8_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant9_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant10_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant11_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant12_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant13_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant14_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant15_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant16_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant17_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant18_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant19_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant20_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant21_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant22_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant23_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant24_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant25_s4 <-read_sheet(ss = "", 
                           sheet = "S4_ResilienceAttributes",
                           range = "A9:M61",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

s4_bind <- bind_rows(respondant1_s4, respondant2_s4, respondant3_s4, respondant4_s4, respondant5_s4, respondant6_s4, respondant7_s4, respondant8_s4, respondant9_s4, respondant10_s4, respondant11_s4, respondant12_s4, respondant13_s4, respondant14_s4, respondant15_s4, respondant16_s4, respondant17_s4, respondant18_s4, respondant19_s4, respondant20_s4, respondant21_s4, respondant22_s4, respondant23_s4, respondant24_s4, respondant25_s4)

```


```{r}
#information Quality Analysis

s4_data_quality_count <- count(s4_bind, s4_bind$information_quality)

s4_data_quality_plot <- ggplot(s4_bind, aes(x = information_quality)) +
  geom_bar()

s4_data_quality_count
s4_data_quality_plot

```

```{r}
# Analyzing if the mechanisms are generally working

s4_mechanism_count <- count(s4_bind, s4_bind$does_the_mechanism_work_as_described_in_your_system)

s4_mechanism_plot <- ggplot(s4_bind, aes(x = does_the_mechanism_work_as_described_in_your_system)) + 
  geom_bar()

s4_mechanism_count
s4_mechanism_plot

```

```{r echo=FALSE}
# This will be for testing text analysis

s4_notes_tokens <- s4_bind %>%
  unnest_tokens(word, notes) %>%
  select(word) %>%
  drop_na()

s4_notes_wc <- s4_notes_tokens %>%
  count(word) %>%
  arrange(-n) 

s4_notes_no_stop_numeric <- s4_notes_tokens %>%
  anti_join(stop_words) %>%
  dplyr::filter(is.na(as.numeric(word)))

#Below here will be making a word cloud

s4_notes_100 <- s4_notes_no_stop_numeric %>%
  count(word) %>%
  arrange(-n) %>%
  head(100)

s4_notes_cloud <- ggplot(data = s4_notes_100, aes(label = word, size = n)) +
  geom_text_wordcloud(aes(color = n), shape = "diamond") +
  scale_size_area(max_size = 15) +
  #scale_color_gradient(colors = c("darkgreen", "blue", "purple")) +
  theme_minimal()

s4_notes_cloud


```

###############################################################################################################################################
Section 5 Analysis

```{r, include=FALSE}
#This will read in all of the data for section 5

respondant1_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant2_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant3_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant4_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant5_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant6_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant7_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant8_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant9_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant10_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant11_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant12_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant13_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant14_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant15_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant16_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant17_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant18_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant19_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant20_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant21_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant22_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant23_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant24_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

respondant25_s5 <-read_sheet(ss = "", 
                           sheet = "S5_CapacitytoImproveClimate",
                           range = "A9:U91",
                           col_names = TRUE,
                           na = "",
                           guess_max = 10000,
                           trim_ws = TRUE,
                           col_types = "c"
                           ) %>%
  as_tibble() %>%
  clean_names()

s5_bind <- bind_rows(respondant1_s5, respondant2_s5, respondant3_s5, respondant4_s5, respondant5_s5, respondant6_s5, respondant7_s5, respondant8_s5, respondant9_s5, respondant10_s5, respondant11_s5, respondant12_s5, respondant13_s5, respondant14_s5, respondant15_s5, respondant16_s5, respondant17_s5, respondant18_s5, respondant19_s5, respondant20_s5, respondant21_s5, respondant22_s5, respondant23_s5, respondant24_s5, respondant25_s5)

```

```{r}
# Text mining response

```

```{r}
#information Quality Analysis

s5_data_quality_count <- count(s5_bind, s5_bind$information_quality)

s5_data_quality_plot <- ggplot(s5_bind, aes(x = information_quality)) +
  geom_bar()

s5_data_quality_count
s5_data_quality_plot

```

```{r echo=FALSE}
# This will be for testing text analysis

s5_notes_tokens <- s5_bind %>%
  unnest_tokens(word, notes) %>%
  select(word) %>%
  drop_na()

s5_notes_wc <- s5_notes_tokens %>%
  count(word) %>%
  arrange(-n) 

s5_notes_no_stop_numeric <- s5_notes_tokens %>%
  anti_join(stop_words) %>%
  dplyr::filter(is.na(as.numeric(word)))

#Below here will be making a word cloud

s5_notes_100 <- s5_notes_no_stop_numeric %>%
  count(word) %>%
  arrange(-n) %>%
  head(100)

s5_notes_cloud <- ggplot(data = s5_notes_100, aes(label = word, size = n)) +
  geom_text_wordcloud(aes(color = n), shape = "diamond") +
  scale_size_area(max_size = 15) +
  #scale_color_gradient(colors = c("darkgreen", "blue", "purple")) +
  theme_minimal()

s5_notes_cloud


```
