---
title: 'Learning Synthesis Paper: Descriptive Statistics'
author: "Meghan Fletcher"
date: "6/8/2022"
output: 
  html_document:
    theme: flatly
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE, message = FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

```

# Load data

```{r}
library(here)
source(here("case_study_analysis", "00-load-libraries.R"))
load(here("case_synth_learning", "data","clean_learning_data.Rdata")) # from 01-prep-data.Rmd
```


# Completeness Table
```{r}
learning_completeness <- clean_learning_data %>% 
  select("question_id", "case_study", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "h") %>% 
  # Gather
  gather(key="type", value="value", 13:ncol(.)) %>%
  mutate(type=stringr::str_to_sentence(type),
         type=factor(type, levels=c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j")))
```

```{r}
# Theme
my_theme <-  theme(axis.text=element_text(size=5),
                   axis.title=element_blank(),
                   strip.text=element_text(size=6),
                   axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"))
                   # Legend
                   #legend.background = element_rect(fill=alpha('blue', 0)))

# Plot data
g <- ggplot(learning_completeness, aes(x=type, y=question_id)) +
  facet_grid(space="free_y", scales="free_y") +
  geom_tile() +
  # Labels
  labs(x="", y="") +
  # Theme
  theme_bw() + my_theme
g
```




# Frequency Table

```{r}
learning_frequnecy_data <- clean_learning_data %>% 
  select("question_id", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j") %>% # no responses for K or L
  # For converting categorical variables in numeric values
   mutate(a = case_when(
    a == "a" ~ 1)) %>% 
  mutate(b = case_when(
    b == "b" ~ 1)) %>% 
  mutate(c = case_when(
    c == "c" ~ 1)) %>% 
  mutate(d = case_when(
    d == "d" ~ 1)) %>% 
  mutate(e = case_when(
    e == "e" ~ 1)) %>% 
  mutate(f = case_when(
    f == "f" ~ 1)) %>% 
  mutate(g = case_when(
    g == "g" ~ 1)) %>% 
  mutate(h = case_when(
    h == "h" ~ 1)) %>% 
  mutate(i = case_when(
    i == "i" ~ 1)) %>% 
  mutate(j = case_when(
    j == "j" ~ 1)) %>% 
  group_by(question_id) %>% 
  mutate_all(~replace(., is.na(.), 0))


learning_frequnecy_counts <- learning_frequnecy_data %>% 
  count(a,b,c,d,e,f,g,h,i,j) 
```



```{r}
Q2211 <- learning_frequnecy_data %>% 
  filter(question_id == "2.2.1.1.") %>% 
  count(a,b,c,d,e,f,g,h,i,j) 
```




















